logging:
  level:
    ROOT: INFO
    springframework:
      web: INFO
server:
  port: ${SERVER_PORT:8080}
spring:
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
